### ISSUE TITLE
Extend mapping of Zenhub tags when generating a changelog

### ISSUE THREAD

**Issue by alansemenov** [enonic/release-tools#24]
Currently we have 4 tags that we are looking for when generating changelog for a new release: _Feature_, _Improvement_, _Bug_ and _Refactoring_. These tags are configured only for those repos that we used to generate changelogs for (xp, lib-admin-ui, app-contentstudio etc.)

Now we started using the changelog generation tool in other repos as well, which don't have these tags but instead have default Zenhub tags that look like this:
 
![image](https://user-images.githubusercontent.com/11612490/92390741-c2a18e00-f11b-11ea-8be5-295df9081aa7.png)

The tool won't find any matching tags, so changelog is generated empty.

If we fix the mapping inside the tool to also include these two default tags then issues won't get excluded from changelogs for repos where custom tags are not configured.

_bug_ -> _Bug_
_enhancement_ -> _Improvement_

**Comment by rymsha** [comment]
I hope I fixed it. Need to test. Looking forward to get some app release to try it on.
