### ISSUE TITLE
auto-merge robot for dependabot

### ISSUE THREAD

**Issue by rymsha** [enonic/release-tools#34]
Currently we use 
protected-branches  (with at least one approval) + auto-approve action + auto-merge action to merge not-failing PRs from Dependabot.

it is not robust as auto- actions often fail for no good reason.
it also introduces complexity for other automations (like SNAPSHOT version auto bump)

The idea is to create a robot that would auto merge Dependabot PRs, if all check pass.

**Comment by alansemenov** [comment]
Will be done in https://github.com/enonic/bot-pull-merger/issues/1
